### ISSUE TITLE
支持 Callback 方式进行调用

### ISSUE THREAD

**Issue by shanderlam** [upyun-dev/discover#2]

**Comment by abbshr** [comment]
相关讨论: https://github.com/nodejs/CTC/issues/12, 这里面也提到了为什么还没把 Promise 铺展开来
相关 PR: https://github.com/nodejs/node/pull/12489
doc: https://nodejs.org/api/util.html#util_util_promisify_original

毕竟是 EcmaScript 语言规范里的东西, V8 也原生支持. 社区也正在把 Promise 融入到核心 API 里.
